version: "3"

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: app_forms_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_forms_volumes:/data/db

  app:
    build: .
    container_name: app_forms
    depends_on:
      - mongodb
    environment:
      - DATABASE_CLIENT_ADDRESS_AND_PORT=mongodb://mongodb:27017/
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/code/.env
    command: ["bash", "-c", "/code/run_tests.sh"]

volumes:
  mongodb_forms_volumes: